#!/bin/bash

key=''
case $1 in
	# EDIT: add remote machines, their keys and hostnames
	machine_1)
		key='path_to_key1.pem'
		hostname='hostname_1'
		;;
	machine_2)
		key='path_to_key2.pem'
		hostname='hostname_2'
		;;
	*)
		;;
esac

if [ -n "$key" ]
then
	ssh -i $key $hostname
else
	echo "Machine $1 does not exist!"
fi

